// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhjuuvtowixfltodtqov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoanV1dnRvd2l4Zmx0b2R0cW92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTY2NTgsImV4cCI6MjA2NzM3MjY1OH0.D2ts86Owxxj-R0Egu-ivl_0oh0PoI55Q6S2brPMfwls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});